---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
  namespace: devops
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: mahikilari/nodejs:0.1
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs
  namespace: devops
spec:
  selector:
    app: nodejs
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 3000
    port: 3000
